version: '3.4'

services:
    samba:
      #image: stanback/alpine-samba
      build: .
      container_name: samba
      volumes:
        - samba-v:/srv/samba/shared

      ports:
        - "137:137/udp"
        - "138:138/udp"
        - "139:139/tcp"
    
      extra_hosts:
        - localhost:${HOST_IP}

networks:
    default:

volumes:
  samba-v:
      